listen_addresses = '*'
port = 5432
max_connections = 100
shared_preload_libraries = 'pg_stat_statements'
logging_collector = on
log_destination = 'stderr'
log_directory = 'log'
log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
log_statement = 'all'
log_min_duration_statement = 0
shared_buffers = '256MB'
work_mem = '8MB'
maintenance_work_mem = '64MB'
effective_cache_size = '1GB'
